apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ml-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ml-service.selectorLabels" . | nindent 8 }}
        version: {{ .Values.image.tag }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http

        env:
        # Из ConfigMap
        - name: MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ include "ml-service.fullname" . }}-config
              key: MODEL_VERSION
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ml-service.fullname" . }}-config
              key: LOG_LEVEL

        # Из Secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "ml-service.fullname" . }}-secret
              key: DATABASE_URL

        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}

        startupProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          failureThreshold: {{ .Values.probes.startup.failureThreshold }}

        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}