apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ml-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}